/* eslint-disable max-len */
import React from 'react';
import {
  View,
} from 'react-native';
import BodyText from '../../../../BodyText';
import Header from '../../../../Header';

const Explanation = function Explanation() {
  return (
    <View>
      <Header>
        Retain Triple Crown rights for Talumet
      </Header>
      <BodyText>
        The promotional rights that interest Feedtech are largely the ones that will be generated by the new deal: public tours of the stable and an official connection with Talumet farm.
      </BodyText>
      <BodyText>
        By excluding horses that win Triple Crown victories from the promotional rights agreement, Talumet eliminates this source of opportunity cost, while Feedtech maintains the rights it is most interested in.
      </BodyText>
      <BodyText>
        For example, Feedtech could tout itself as ‘The Official Feed Company of Talumet Farm’, even while Talumet sells the individual promotional rights of a Triple Crown winner to the highest bidder.
      </BodyText>
    </View>
  );
};

export default Explanation;
