/* eslint-disable max-len */
import React from 'react';
import {
  View,
} from 'react-native';
import BodyText from '../../../../BodyText';
import I from '../../../../ItalicText';

const Body = function Body() {
  return (
    <View>
      <BodyText>
        Under the tentative agreement, Feedtech would pay the fixed costs for the expansion of facilities, which would amount to an estimated $4.3 million. The new stables would be named <I>Feedtech Stables</I> and be open for public tours two hours of each week. Feedtech would also be given the exclusive rights to use Talumet Farm and its horses in promotional material.
      </BodyText>
      <BodyText>
        Talumet would bear all breeding and care costs for the additional horses (estimated annual cost of $2.4 million), but would maintain control over all non-promotional revenues. The naming and promotional rights agreement with Feedtech would expire after 10 years, though it could be re-negotiated and renewed.
      </BodyText>
      <BodyText>
        The new facilities would house 10 horses, allowing Talumet to expand its slate of racing thoroughbreds by that number. The horses in the existing stables earn, on average, $20,000 per race, and participate in six races per year.
      </BodyText>
      <BodyText>
        If race purses make up 40% of the revenue generated by each horse, what will be the net annual profit generated by the expansion?
      </BodyText>
    </View>
  );
};

export default Body;
/* eslint-enable max-len */
