/* eslint-disable max-len */
import React from 'react';
import {
  View,
} from 'react-native';
import BodyText from '../../../../BodyText';

const Body = function Body() {
  return (
    <View>
      <BodyText>
        As evidenced by the previous table, the vast majority of promotional revenues have always come from the sale of promotional rights for individual star horses.
      </BodyText>
      <BodyText>
        Promotional revenue generated by other sources (e.g., promotional rights for the Talumet name) have fallen recently, declining $2,500 annually on average over the past four years.
      </BodyText>
      <BodyText>
        A team member suggests that projections for ‘other’ promotional revenue should incorporate $2,500 annual declines, are you inclined to agree or disagree?
      </BodyText>
    </View>
  );
};

export default Body;
